import { ExternalLink, ShieldCheck } from 'lucide-react-native';
import { View } from 'react-native';
import { AppText } from '@/components/app-text';
import { PageScreen } from '@/components/page-screen';
import { SectionCard } from '@/components/section-card';
import { useAppTheme } from '@/contexts/theme-context';
import { SettingRow } from '@/components/setting-row';
import { openWebsite } from '@/lib/website';
export default function PrivacySecurityScreen() { const { colors } = useAppTheme(); const icon = <ExternalLink color={colors.textMuted} />; return <PageScreen title="Privacy & security" subtitle="How Jela protects this app"><View style={{ gap: 12 }}><SectionCard><ShieldCheck color={colors.success} /><AppText variant="title">Secure by design</AppText><AppText tone="muted">Sessions use Android secure storage. AI provider and payment secrets stay on Jela AI servers. Payment callbacks are verified before any plan is activated.</AppText></SectionCard><SectionCard title="Private profile media"><AppText tone="muted">Avatars and conversation attachments stay in protected storage and are delivered with short-lived access.</AppText></SectionCard><SettingRow title="Privacy Policy" icon={icon} onPress={() => void openWebsite('privacy')} /><SettingRow title="Terms of Use" icon={icon} onPress={() => void openWebsite('terms')} /><SettingRow title="Help" icon={icon} onPress={() => void openWebsite('help')} /><SettingRow title="Contact" icon={icon} onPress={() => void openWebsite('contact')} /><SettingRow title="Pricing" icon={icon} onPress={() => void openWebsite('pricing')} /><SettingRow title="Documentation" icon={icon} onPress={() => void openWebsite('documentation')} /><SettingRow title="Visit Jela AI website" icon={icon} onPress={() => void openWebsite('website')} /></View></PageScreen>; }
